environment: ''
domains: []

auth:
  domain: auth.bts-crew.com
  realm: ''

image:
  tag: ''

smtp:
  host: ''
  port: ''
  encryption: ''
  auth: ''

logging:
  driver: monolog

google-analytics-code: ''

resources:
  memory: ''
