daysUntilStale: 30
daysUntilClose: 14
exemptLabels:
  - keep-open
  - urgent
staleLabel: stale
markComment: >
  This issue has been automatically marked as stale because it has not had
  recent activity. It will be closed in 2 weeks if no further activity occurs. 
  To keep it open please talk to the development team.
closeComment: >
  This issue has been automatically closed as it has not had recent activity.
  You can re-open this issue if you feel it should still be worked on.
pulls:
  daysUntilStale: 14
  markComment: >
    This pull request has been automatically marked as stale because it has not had
    recent activity. It will be closed in 2 weeks if no further activity occurs.
