apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "website-v4.fullname" . }}
  labels:
    {{- include "website-v4.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "website-v4.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      name: {{ include "website-v4.fullname" . }}
      labels:
        {{- include "website-v4.labels" . | nindent 8 }}
    spec:
      containers:
        - name: app
          image: 'ghcr.io/backstage-technical-services/website:{{ .Values.image.tag }}'
          imagePullPolicy: Always
          envFrom:
            - secretRef:
                name: {{ include "website-v4.fullname" . }}
            - configMapRef:
                name: {{ include "website-v4.fullname" . }}
          volumeMounts:
            - name: backups
              mountPath: /var/www/storage/app/backups
            - name: profiles
              mountPath: /var/www/public/images/profiles
            - name: elections
              mountPath: /var/www/resources/elections
            - name: resources
              mountPath: /var/www/resources/resources
            - name: breakages
              mountPath: /var/www/resources/breakages
          resources:
            requests:
              memory: '{{ .Values.resources.memory }}'
            limits:
              memory: '{{ .Values.resources.memory }}'
      volumes:
        - name: backups
          hostPath:
            path: /opt/data/backstage/website-v4/{{ .Values.environment }}/backups
        - name: profiles
          hostPath:
            path: /opt/data/backstage/website-v4/{{ .Values.environment }}/profiles
        - name: elections
          hostPath:
            path: /opt/data/backstage/website-v4/{{ .Values.environment }}/elections
        - name: resources
          hostPath:
            path: /opt/data/backstage/website-v4/{{ .Values.environment }}/resources
        - name: breakages
          hostPath:
            path: /opt/data/backstage/website-v4/{{ .Values.environment }}/breakages
      nodeSelector:
        bnjns.uk/owner: backstage
      tolerations:
        - key: bnjns.uk/reserved-for
          operator: Equal
          value: backstage
          effect: NoSchedule
