name: 🐛 Report a Bug
description: Use this to report when something doesn't work as expected.
labels:
  - status/triage
  - type/bug
type: Bug
body:
  - type: checkboxes
    attributes:
      label: Confirm there isn't an existing issue for this
      description: Please search to see if an issue already exists for the bug you encountered
      options:
      - label: I have searched the existing issues
        required: true
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: |
        Provide a brief summary of the bug
        
        Avoid using words like buggy/broken/not working - it's really important to know exactly what's not working as expected
    validations:
      required: true
  - type: textarea
    id: actual-behaviour
    attributes:
      label: Actual behaviour
      description: |
        What is happening that you think shouldn't happen?
        
        Pictures paint a thousand words and really help us understand what's going on - include screenshots if possible
    validations:
      required: true
  - type: textarea
    id: expected-behaviour
    attributes:
      label: Expected behaviour
      description: What do you expect the website should do?
    validations:
      required: true
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to reproduce
      description: |
        Provide as much information regarding what you were doing when the bug occurred
        
        If you were saving data to the site, please also include it here (with any sensitive details redacted) in a ```code block``` or provide a reference to it
    validations:
      required: true
  - type: textarea
    id: when
    attributes:
      label: When did it happen?
      description: This will let us see if there is any helpful information in the server logs
    validations:
      required: true
  - type: dropdown
    id: urgency
    attributes:
      label: Urgency
      description: How quickly does this need to be resolved? Is this preventing you or anyone else from being able to do something you/they need to?
      options:
        - Low
        - Medium
        - High
        - Very high
      default: 1
    validations:
      required: true
