name: ✨ Request a Feature
description: Use this when you would like some new functionality to be added.
labels:
  - status/triage
  - type/feature
body:
  - type: checkboxes
    attributes:
      label: Confirm there isn't an existing issue for this
      description: Please search to see if an issue already exists for this feature request
      options:
      - label: I have searched the existing issues
        required: true
  - type: textarea
    id: request
    attributes:
      label: Request
      description: Describe your request, using as much detail as you can. Don't be afraid to any planning you've already done, and take advantage of formatting and lists to make it easier to read!
    validations:
      required: true
  - type: input
    id: domain
    attributes:
      label: Where should this go?
      description: Is there a certain section/area of this website this would fit into?
    validations:
      required: false
  - type: textarea
    id: rationale
    attributes:
      label: Rationale
      description: Why should this be implemented? How does this benefit members, the committee, our clients or the university?
    validations:
      required: true
  - type: dropdown
    id: urgency
    attributes:
      label: Urgency
      description: How quickly does this need to be implemented? If theres a certain date or event this needs to be done by, include that in the "Other details" section below.
      options:
        - Low
        - Medium
        - High
        - Very high
      default: 1
    validations:
      required: true
  - type: textarea
    id: other-details
    attributes:
      label: Other details
      description: Are there any other details you think we should know?
    validations:
      required: false
