name: Build

permissions:
  contents: read
  packages: read

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up builder
        run: |
          docker buildx create \
            --name container \
            --driver docker-container
      - name: Log into the registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin
      - name: Build image
        run: |
          docker buildx build \
            --builder container \
            --platform linux/amd64,linux/arm64 \
            -f .docker/prod.Dockerfile \
            -t ghcr.io/${{ github.repository }}:${{ github.sha }} \
            .
