name: Build

permissions:
  contents: read
  packages: read
  id-token: write

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build image
    runs-on: ${{ matrix.runner }}
    env:
      ECR_URL: ${{ vars.ECR_BASE_URL }}/backstage-website-v4
    strategy:
      fail-fast: false
      matrix:
        include:
          - runner: ubuntu-22.04
            tag: amd64
          - runner: ubuntu-22.04-arm
            tag: arm64
    steps:
      - uses: actions/checkout@v4
      - name: Set up builder
        uses: docker/setup-buildx-action@v3
      - name: Log into the GitHub container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: eu-west-1
          role-to-assume: ${{ vars.IMAGE_PUSH_ROLE_ARN }}
      - name: Log into ECR
        uses: aws-actions/amazon-ecr-login@v2
      - name: Build image
        uses: docker/build-push-action@v6
        with:
          push: false
          file: .docker/prod.Dockerfile
          cache-from: type=registry,ref=${{ env.ECR_URL }}:cache-${{ matrix.tag }}
          tags: |
            ${{ github.repository }}:${{ github.sha }}-${{ matrix.tag }}
