name: Checks

on:
  pull_request:
    branches:
      - main

jobs:
  formatting:
    name: Formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - uses: actions/setup-node@v4
        with:
          node-version: latest
      - run: yarn install --frozen-lockfile
      - run: yarn check:format

  phpstan:
    name: PHPStan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: 'false'
      - uses: shivammathur/setup-php@v2
        with:
          php-version: 8.4
          tools: composer
      - run: composer install --no-interaction --prefer-dist
      - run: |
          ./vendor/bin/phpstan analyse \
            --memory-limit 1G \
            --error-format github
  test:
    name: Tests
    runs-on: ubuntu-latest
    permissions:
      checks: write
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: 'false'
      - uses: shivammathur/setup-php@v2
        with:
          php-version: 8.4
          tools: composer
          coverage: xdebug
      - uses: actions/setup-node@v4
        with:
          node-version: latest
      - name: Install PHP dependencies
        run: composer install --no-interaction --prefer-dist
      - name: Install JS dependencies
        run: yarn install --no-dev --frozen-lockfile
      - name: Configure app
        run: |
          cp .env.example .env
          php artisan key:generate
      - name: Run tests
        env:
          XDEBUG_MODE: coverage
        run: |
          ./vendor/bin/pest \
            --log-junit tests/results/junit.xml \
            --coverage-clover tests/results/coverage.xml \
            --ci
      - uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: tests/results
      - uses: ctrf-io/github-test-reporter@v1
        if: success() || failure()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          report-path: 'tests/results/junit.xml'
          integrations-config: |
            {
              "junit-to-ctrf": {
                "enabled": true,
                "action": "convert",
                "options": {
                  "output": "./ctrf-reports/ctrf-report.json",
                  "toolname": "junit-to-ctrf",
                  "useSuiteName": true
                }
              }
            }
          pull-request: true
          use-suite-name: true
          collapse-large-reports: true
          group-by: suite
          always-group-by: true
          overwrite-comment: true
          always-latest-comment: true
          comment-tag: ctrf-test-report
