name: Test

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: kirschbaumdevelopment/laravel-test-runner:8.0
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: Install OS dependencies
        run: |
          apt-get update -y
          apt-get install -y php8.0-xdebug
      - name: Install PHP dependencies
        run: composer install --no-interaction --prefer-dist
      - name: Install JS dependencies
        run: yarn install --no-dev --frozen-lockfile
      - name: Configure app
        run: |
          cp .env.example .env
          php artisan key:generate
      - name: Run tests
        run: |
          export XDEBUG_MODE=coverage
          ./vendor/bin/phpunit \
            --log-junit tests/results/junit.xml \
            --coverage-clover tests/results/coverage.xml
      - uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: tests/results

  sonarcloud:
    if: github.repository == 'backstage-technical-services/laravel-site'
    runs-on: ubuntu-latest
    needs:
      - test
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/download-artifact@v3
        with:
          name: test-results
          path: tests/results
      - name: SonarCloud scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
