name: Test

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: kirschbaumdevelopment/laravel-test-runner:8.0
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: Install PHP dependencies
        run: composer install --no-interaction --prefer-dist
      - name: Install JS dependencies
        run: yarn install --no-dev --frozen-lockfile
      - name: Configure app
        run: |
          cp .env.example .env
          php artisan key:generate
      - name: Run tests
        run: |
          export XDEBUG_MODE=coverage
          ./vendor/bin/phpunit \
            --log-junit tests/results/junit.xml \
            --coverage-clover tests/results/coverage.xml
      - uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: 'tests/results/'